import os
import json
from utils import ensure_directory, write_json, append_to_file, sanitize_filename

OUTPUT_BASE_DIR = "Video_Project"

def create_project_structure(project_title):
    safe_title = sanitize_filename(project_title)
    base_dir = os.path.join(os.getcwd(), OUTPUT_BASE_DIR)
    project_dir = os.path.join(base_dir, safe_title)
    assets_dir = os.path.join(project_dir, "Assets")
    
    ensure_directory(base_dir)
    ensure_directory(project_dir)
    ensure_directory(assets_dir)
    
    return {
        "project_dir": project_dir,
        "assets_dir": assets_dir,
        "image_prompts_path": os.path.join(project_dir, "Image_Prompts.txt"),
        "editing_notes_path": os.path.join(project_dir, "Editing_Notes.json"),
        "manifest_path": os.path.join(project_dir, "manifest.txt")
    }

def add_image_prompt(prompts_path, index, phase, prompt):
    line = f"[{str(index).zfill(3)}_{phase}] {prompt}"
    append_to_file(prompts_path, line)

def generate_editing_notes(notes_path, processed_beats, asset_results):
    notes = []
    
    for beat_data, asset_data in zip(processed_beats, asset_results):
        note = {
            "index": beat_data['index'],
            "beat_text": beat_data['beat'],
            "phase": beat_data['phase'],
            "asset_filename": asset_data['asset'].get('filename'),
            "asset_type": asset_data['asset'].get('type'),
            "instruction": asset_data['asset'].get('instruction'),
            "sfx": beat_data['sfx'],
            "overlay": asset_data.get('overlay')
        }
        notes.append(note)
    
    write_json(notes, notes_path)
    return notes

def log_error(manifest_path, index, phase, error_msg):
    line = f"[ERROR] [{str(index).zfill(3)}_{phase}] {error_msg}"
    append_to_file(manifest_path, line)

def log_success(manifest_path, index, phase, asset_filename):
    line = f"[SUCCESS] [{str(index).zfill(3)}_{phase}] {asset_filename}"
    append_to_file(manifest_path, line)

def initialize_manifest(manifest_path, project_title):
    with open(manifest_path, 'w') as f:
        f.write(f"=== MANIFEST: {project_title} ===\n")
        f.write(f"Generated by YouTube Visual Assets Generator\n")
        f.write("=" * 50 + "\n\n")

def finalize_outputs(paths, processed_beats, asset_results, project_title):
    initialize_manifest(paths['manifest_path'], project_title)
    
    for beat_data, asset_data in zip(processed_beats, asset_results):
        if asset_data['asset'].get('success'):
            log_success(
                paths['manifest_path'],
                beat_data['index'],
                beat_data['phase'],
                asset_data['asset']['filename']
            )
        else:
            log_error(
                paths['manifest_path'],
                beat_data['index'],
                beat_data['phase'],
                asset_data['asset'].get('error', 'Unknown error')
            )
    
    generate_editing_notes(paths['editing_notes_path'], processed_beats, asset_results)
    
    return {
        "project_dir": paths['project_dir'],
        "assets_count": len(asset_results),
        "successful": sum(1 for a in asset_results if a['asset'].get('success')),
        "prompts_generated": sum(1 for a in asset_results if a.get('ai_prompt'))
    }
